### ISSUE TITLE
Krill MUST NOT create only a single AFI ASPA

### ISSUE THREAD

**Issue by jayb-github** [NLnetLabs/krill#1063]
Per this SIDROPS-list discussion: https://mailarchive.ietf.org/arch/msg/sidrops/QtMzLIz0yJwNCUVdvC_1cJjEIHc/

... an ASPA specified for only one AFI will result in RPs signaling an AS0 VAP for the other AFI.

It would better for Krill to not allow an operator to create such a counter-intuitive and probably unexpected situation, but instead to require that after performing the requested operation, explicit ASPAs covering both AFIs MUST exist.

**Comment by timbru** [comment]
Indeed.. okay, the ASPA support in Krill was made at a time when the restrictions had not yet been fully crystallised.

I will make a fix that forces the operator to make an explicit choice in new / updated objects. If the user intended to have an AS0 only for one address family then they can specify this explicitly, rather than getting this result implicitly, which may well surprise them indeed.

I will first finalise release 0.13.0 this Monday based on 0.13.0-rc6 without further changes. This is needed as it will allow Publication Servers to overcome issue #1023.

Then I will make a very quick follow up 0.13.1-rc1 with a fix for this, and #1061 and #1058.

**Comment by timbru** [comment]
Contrary to the earlier message.. we decided to include this in release 0.13.0 which is going out in a few moments
