### ISSUE TITLE
Set up pre-release acceptance test environment.

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/krill#17]

**Comment by ximon18** [comment]
Initial version based on GitHub Actions and [rpki-deploy](https://github.com/NLnetLabs/rpki-deploy/tree/master/terraform/krill-e2e-test) has been operating since Nov 11 2019 (implemented in commits 2c5ce94a - 2d57d9f6) and assisted with [v0.3.0](https://github.com/NLnetLabs/krill/releases/tag/v0.3.0) pre-release testing.

Testing is done per commit to any branch with Krill being built from that branch as a Docker container deployed alongside Dockerized versions of supporting tools nginx, rsyncd and relying parties fort validator, octorpki, rcynic, ripe rpki ncc validator 3 and routinator). Krill is configured as a TA and CA with ROAs and the RPs are queried for the result of their attempts to fetch the ROAs from Krill using its TAL. Results are visible in the [GitHub Actions UI](https://github.com/NLnetLabs/krill/actions?query=workflow%3A%22E2E+Test%22).

GitHub Actions via VMs in Azure US East orchestrates deployment and captures logs. Actual deployment is done using [Terraform](https://www.terraform.io/) to a VM in Digital Ocean in Amsterdam, with the Docker daemon being managed by [Docker Machine](https://docs.docker.com/machine/) and [Docker Compose](https://docs.docker.com/compose/). Bash scripts in custom RP Docker images fetch the Krill TAL and install it (after converting it from HTTPS based to RSYNC based) where the RP can find it. The same scripts then invoke the RP and extract, post-process and output the ROAs to the Docker logs in a form that a Bash test script running on the GitHub Actions host VM can parse.

This initial version works and is reasonably quick (approx 10-15 mins) but despite use of a retry-on-error strategy still occasionally requires that the job be retried due to some intermittent failure. Given the number of moving parts involved this may be inevitable.

However, possible improvements could include using:
- A Digital Ocean private Docker registry (we already have one) to eliminate some container building that is identical on every run and depends on external package repo servers.
- A Python xUnit framework instead of a Bash re-invented-here approach (which has already been the cause of several bumps).
- A Python based Krill API client generated from a Krill OpenAPI spec, replacing `krillc` process management and shell based result post-processing with native Python use of the REST API and Python language based processing of first class response objects).
- A Python based RTRLIB wrapper for communicating as an RTR client with the RP RTR endpoints instead of fetching their CLI output or internal state and munging it into a form that can be scraped from Docker logs.
- Fixing/improving Krill and the RPs to move away from use of an RSYNC based TAL to a HTTPS based TAL.
- Etc.
