### ISSUE TITLE
Problem SSL Certificate

### ISSUE THREAD

**Issue by diditonf** [NLnetLabs/krill#194]
Hi,

When i'm trying to execute krillc i'm getting this error.

> Request Error: https://187.16.255.102:3000/api/v1/cas: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1924: (self signed certificate)

**Comment by timbru** [comment]
This happens because by default Krill will generate a self-signed certificate for use with HTTPS. 

Our recommended way to deal with this, is to put a proxy like nginx, or apache, or $your-choice, in front of Krill. Such proxy servers are generally kept well up to date w.r.t. HTTPS best practices (eg ciphers and what not), and can be set up to use real, well trusted, certificates much more easily. E.g. using letsencrypt and its certbot.

The CLI will only trust self-signed certificates if you run it on the same host - or rather if you try to connect to localhost. We should a add a feature - thanks for reminding me! - that will allow users to tell the CLI to trust a specific certificate. I created an issue for that now (#195). This should be useful in certain set ups where you don't mean to expose Krill to others, and generating a trusted certificate is cumbersome. I am not yet whether this will make it to the 0.5 release, or that it will have to wait a bit longer.

It should also be possible to configure Krill to use a real certificate by replacing the `key.pem` and `cert.pem` files in the `ssl` directory under your data dir. However, this has not been tested because we believe that one should not put Krill on a public network without a proxy.

Finally, I am sure you are aware, but for the record. Please use an unguessable token when exposing Krill on any kind of public network :)

**Comment by diditonf** [comment]
Hi,

But when i try using localhost i'm getting this error to start krill.

> root@krill:/home# krill -c ./data/krill.conf
> Error parsing config file: ./data/krill.conf, error: invalid IP address syntax for key `ip`
> root@krill:/home#

> ip             = "localhost"
> port           = 3000

**Comment by timbru** [comment]
Access Forbidden indicates that your token does not match the server token.

**Comment by timbru** [comment]
I believe that the original issue is resolved. But if you encounter anything, please feel free to re-open or create a new issue.
