### ISSUE TITLE
Questions regarding using Krill as embedded TA

### ISSUE THREAD

**Issue by dadepo** [NLnetLabs/krill#211]
I am trying to setup a lab environment using Krill and Routinator, and for this, I need to set up Krill to use it's embedded TA. But it seems the Tal generated by Krill does not work when used in Routinator. This is probably due to something I am doing wrong, so pointers would be appreciated.

This is the current setup.

I have krill running and when I make a request to `https://localhost:3000/ta/ta.tal` I get the tal. For example this:

```
https://localhost:3000/ta/ta.cer

MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4I10vJJ9gNLgYzm5w6m0
m/hlmMYL2qSqdzWNL1U3Oehqov68cGL0J2gbiE0NIVSIOCKODhv1KI+oA2yCToML
+cNiou5cDz3zIF/jrHbeNz5baFqeIfwSRP1eunTM4XTT0RjHsJqh0sj7zdfIYWdN
sK4rV2giqtGMVR+8O44SdYoP2ewJ3vo4zh7inmTkwZyj2yFAUS3G5sQ5I0vHHkM6
3ZzojJeXbjl2biufCGr+i7lDc7vL6W6TO4rKBpX04AKX7T0OpUi+ZiN5OKc6bTx5
sMO1tRPpuaXwByifanCmLA1SOaNDb+NSk5mJVSzTzIj1JiNvXQLsELppw0Vl3dPX
FQIDAQAB
```

Then I remove all the preconfigured tal in Routinator, copy the text above into a file and place it in the location Routinator expects the tals. When I run `routinator vrps` I get:

```
No valid trust anchor for TAL ta
ASN,IP Prefix,Max Length,Trust Anchor
```

I noticed the TAL URI was https, so I decided to give it a shot using rsync. To do this, I found out that the TA is placed in the `/data/repo/rsync/current/ta/0/<rand-hex-string>.cer`. So I set up rsync to serve the file, updated the TAL to replace the https path with the rsync path. That also did not work.

I then used another validator to see if that works with the tal. It does not, but I was able to get an error message that showed that the public key extracted from the downloaded certificate does not match the public key in the tal.

So my questions are:

- What could I be doing wrong in my procedure that could lead to such a mismatch of the public key?
- Is there a way to retrieve the tal from the cli, instead of having to use `https://localhost:3000/ta/ta.tal` endpoint?
- Is there a way to configure the location on the file to something like `/data/repo/rsync/current/ta/ta.cer`? the current behaviour of having it as /data/repo/rsync/current/ta/0/<rand-hex-string>.cer makes having a stable location for the cert impossible.

Thanks!

**Comment by timbru** [comment]
Hi Dadepo,

Thank you for reporting this, and my apologies that this was not documented more clearly.

Issue #125 was created for this. However, I am very reluctant to spend time on this, because:
1. it is relatively hard to do because of internals
2. the TA in Krill is for testing purposed only
3. this behaviour is actually allowed by [RFC 8630](https://tools.ietf.org/html/rfc8630)
4. routinator will have to support this at some point

I will talk to Martin about adding support to retrieve the certificate on a TAL using https in routinator.

Until that time you can indeed hack around this, as we have been doing in our own test setup. To do so you will need to download the the ta.cer file using something like curl or wget using the uri that is on the TAL.

Then place this file in a directory of your choice and create a module for it in your rsyncd. Do not place it in the 'current' dir where the actual CA certificates are published, it will be removed if you do.

Then update the TAL and replace the URI with the appropriate rsync URI.

**Comment by timbru** [comment]
update:

As it turns out routinator already supports fetching the TA certificates in TALs over https. What is likely the case here, is that routinator rejects the self-signed certificate that Krill uses.

You have two options:
1. Put nginx (or $proxy) in front of krill and set it up with letsencrypt (or $$ cert)

Use this if you intend to run your test instance on the public internet. Dedicated proxies are much better at proper https than the embedded server.

2. Tell routinator about the certificate

The generated certificate is stored under `$data_dir/ssl/cert.pem`. Tell routinator where to find this file using the option `--rrdp-root-cert <PATH>`.

**Comment by AlexanderBand** [comment]
@dadepo For what it's worth: if it's for a quick and dirty test, I tried putting a real Let's Encrypt certificate in Krill's `/ssl` directory and that seemed to worked. For everything more elaborate, setting up nginx like Tim suggests is a much better idea.

**Comment by ximon18** [comment]
> Until that time you can indeed hack around this, as we have been doing in our own test setup. 

FYI the part of our E2E tests that handles this hack is a Bash `install_tal()` function defined [here](https://github.com/NLnetLabs/rpki-deploy/blob/1396c5a9202625ba7914126b4f7c1359c1c00434/terraform/krill-e2e-test/lib/docker/relyingparties/base/my_funcs.sh#L128),

**Comment by dadepo** [comment]
Thanks all for the input, and apologies for silence; just getting around to looking into this again.

It seems the issue I am running to is quite different. I dug around a little bit more and found out my setup for some reason is failing the check found in [this section of the code](https://github.com/NLnetLabs/rpki-rs/blob/21ca60c3a43c913e2a4bad2995f74aeb446c8234/src/cert/mod.rs#L167) in `rpki-rs`

```
        // 4.8.3. Authority Key Identifier. May be present, if so, must be
        // equal to the subject key indentifier.
        if let Some(ref aki) = self.authority_key_identifier {
            if *aki != self.subject_key_identifier {
                return Err(ValidationError);
            }
        }
```

The `Authority Key Identifier` ends up not being the same as `Subject key identifier`.

I am following the set up instructions in the docs [here](https://rpki.readthedocs.io/en/latest/krill/testing.html#setting-up-the-configuration) and in [this issue](https://github.com/NLnetLabs/krill/issues/168)  as some of the instructions in the doc is out of date.

Any pointers to what I could be doing wrong?

**Comment by timbru** [comment]
I think you are trying to use the certificate issued by your ta to your child, under `/data/repo/rsync/current/ta/0/<something>.cer`, rather than its own self-signed certificate which is not written to disk, but which can be retrieved at:

https://localhost:3000/ta/ta.cer
