### ISSUE TITLE
Add testbed TA and repo UI for easier testing

### ISSUE THREAD

**Issue by timbru** [NLnetLabs/krill#306]
So that we can run a service where Krill users can just register their test Krill instance as a child and publisher.

**Comment by ximon18** [comment]
Handy links for review of the initial POC:
- https://github.com/NLnetLabs/krill/compare/0.8.0-RC-dev...testbed-poc
- https://github.com/NLnetLabs/lagosta/compare/testbed-poc
- https://testbed-poc.aws.nlnetlabs.nl/#/testbed

Review feedback gathered so far from @timbru and @AlexanderBand:
- [ ] Don't link from the top-left Krill logo to the Krill root page.
- [ ] Add a disclaimer that this is for testing, established CA/repo parent-child relationships may disappear at any time and can be deleted by anyone. Should also cover that you can claim in this test hierarchy any resources with ROAs, even those of other people, as being able to claim real ROAs permits testing of the BGP integration in Krill
- [ ] Make any not-yet-translatable strings translatable.
- [ ] Blog about it and link to the blog from the testbed page (to explain that it is a separate test RPKI hierarchy for example)
- [ ] Use a dedicated deployment (e.g. on AWS) with its own monitoring (can re-use current Prometheus and Grafana instance but have separate Grafana dashboard) and logging (use a new AWS S3 bucket)
- [ ] Final deployment should be at https://testbed.rpki.nlnetlabs.nl/ (redirecting to /#/testbed)
- [ ] Make the page layout it a bit wider (even on a 960 wide browser window it becomes too narrow).
- [ ] Grant the testbed CA all resources:
```
asns = "0-4294967295"
v4 = "0.0.0.0-255.255.255.255"
v6 = "::0/0"
```
- [ ] Final deployment should be at https://testbed.rpki.nlnetlabs.nl/ (redirecting to /#/testbed)
 Make the TAL available with filename `test.tal` so that relying party software such as Routinator that report the Trust Anchor name based on the filename report a more useful name than 'ta'.
