### ISSUE TITLE
no rsync link in my testbed tal

### ISSUE THREAD

**Issue by ychlgdr** [NLnetLabs/krill#624]
**Hello~ I have a little confusion while running a test environment myself.May i ask why is there no rsync link in the tal of my testbed? My krill and rsyncd configuration files are as follows, thank you very much！**
```
admin_token = "***********"
data_dir = "/home/krill/data/"
pid_file = "/home/krill/data/krill.pid"
log_file = "/home/krill/data/krill.log"
service_uri = "https://172.17.0.2/"
[testbed]
rrdp_base_uri = "https://172.17.0.2/rrdp/"
rsync_jail = "rsync://172.17.0.2/repo/"
ta_aia = "rsync://172.17.0.2/ta/ta.cer"
ta_uri = "https://172.17.0.2/ta/ta.cer"
```
```
uid = nobody
gid = nogroup
max connections = 50
socket options = SO_KEEPALIVE

[repo]
path = /home/krill/data/repo/rsync/current/
comment = RPKI repository
read only = yes

[ta]
path = /home/krill/data/rsync_cer/ 
comment = ca.cer
read only = yes
```
And here is my testbed tal 
![image](https://user-images.githubusercontent.com/39005242/128482086-a60ef40f-fb6d-47f6-9fa6-e82a03730959.png)

**Comment by ychlgdr** [comment]
btw,my environment is Ubuntu 20.04.2 LTS in docker

**Comment by timbru** [comment]
Hi!

Ah yes, the simple answer is we forgot to include it.

The more nuanced answer is that it turned out to be a bit of hassle to do this when we looked at this a long time ago, and since we were then using the TA/testbed support only for our own testing we figured we might as well copy the certificate over manually and add the rsync URI to the TAL ourselves. As a work around you can do this as well. Just add "rsync://172.17.0.2/ta/ta.cer" to the TAL - provided that you set up the rsync module for it.

But, I agree that now that we are exposing the testbed options to all users, this should work. So I have moved this issue onto the todo list for our coming 0.9.2 release.

Tim

**Comment by ychlgdr** [comment]
> Hi!
> 
> Ah yes, the simple answer is we forgot to include it.
> 
> The more nuanced answer is that it turned out to be a bit of hassle to do this when we looked at this a long time ago, and since we were then using the TA/testbed support only for our own testing we figured we might as well copy the certificate over manually and add the rsync URI to the TAL ourselves. As a work around you can do this as well. Just add "rsync://172.17.0.2/ta/ta.cer" to the TAL - provided that you set up the rsync module for it.
> 
> But, I agree that now that we are exposing the testbed options to all users, this should work. So I have moved this issue onto the todo list for our coming 0.9.2 release.
> 
> Tim

Copy that ,Thank you for you reply,hope you have a beautiful day !
