### ISSUE TITLE
Child CAs in krill are not completely deleted after using the  "krillc children remove" command

### ISSUE THREAD

**Issue by racompton** [NLnetLabs/krill#781]
After a child is created in krill using the "krillc children add" command, it is not fully deleted after using the "krillc children remove" command to delete it.  The command "krillc children info" shows that the child does not exist but the web UI still shows the child CA.  Also in the web UI, it seems that the deleted child CA still shows the repository and is still refreshing the repository.

**Comment by timbru** [comment]
I realise that this is not very clear from the documentation where we seem to talk about children mostly from the parent CA perspective..

But in short, the child CA still shows up in the UI. Because that CA still exists. It may no longer be recognised by its parent, but the child itself was not deleted. The child still exists *and* it still thinks it has its parent. It will keep trying to call its parent, and be rejected. But unfortunately there is no unambiguous support in the protocol (RFC6492) that allows the child to conclude without doubt that the parent removed it... so it keeps trying until you remove the parent for this child:

https://krill.docs.nlnetlabs.nl/en/stable/cli.html#krillc-parents-remove

Similarly, the child continues to publish in its repository. Krill CAs can have 0 or more parents, but they must have 1 repository. Once added you cannot remove the repository, although you could migrate to a new one:

https://krill.docs.nlnetlabs.nl/en/stable/ca-migrate-repo.html

What you are most likely after is deleting the child's actual CA - not the child relation it has to your (its parent) CA. You can remove a CA using the CLI:

https://krill.docs.nlnetlabs.nl/en/stable/cli.html#krillc-delete

Hope this helps, closing this for now.
