### ISSUE TITLE
Register CA error

### ISSUE THREAD

**Issue by gitthehit** [NLnetLabs/krill#805]
According to the blog "making a krill sanctuary", i successfully set up my own local testbed environment. While I tried to register a CA which also on my local, it says that my local testbed CA does not have resources
![9APAN0DL~0`9{L2Y%JT0XG4](https://user-images.githubusercontent.com/49119921/159436931-16998b76-48f8-4d3e-a28a-849e000a8558.png)
.

**Comment by timbru** [comment]
Hi again. Which version are you running?

I looks like you tried adding the child CA before the testbed CA got its resources.

You can try `krillc bulk refresh` from the command line. Or go the the `/index.html#/cas/testbed` path on your Krill UI and try hitting the "Refresh Parents" link on the parents tab.

I am finalizing a new release candidate at the moment: 0.9.5-rc7. This ca-parent sync logic is one of the things that changed and I don't believe that this issue exists in the target rc version - but I will double check once more to be sure.

**Comment by gitthehit** [comment]
Hi, my current version is 0.9.4.

I don't have any resources for my testbed CA. I thought it does not need resources. 

I am running it in my own virtual environment. I want to be able to build RPKI framework without relying on five RIRs. Is it possible to add children without acquiring resources？

Thanks.

**Comment by timbru** [comment]
If you use the built-in testbed support than a testbed CA should be created automatically with ALL resources. Did you remove them somehow per chance? I.e. did you do something like:

`krillc children update --ca ta --child testbed ...`

CAs need to have resources in order to have children. In the test context it should be safe to use ALL (even public) resources for this because RPs would not use your test TA in production settings, and it allows you to test with your real resources.

Have you tried the parent refresh option?

**Comment by gitthehit** [comment]
Yes, I have refreshed it.

I use private address to build testbed support because I don't have a domain name. It seems testbed CA doesn't get any resources.

Is it possible that my configuration is wrong?

![4~Q1ZW%6%{5DJ~R`G74MJ1Z](https://user-images.githubusercontent.com/49119921/159468776-da28981c-062b-4aa1-85d6-6ead1b28a034.png)
![CX5 ~396ZJ0Z`9}{JE01D5H](https://user-images.githubusercontent.com/49119921/159469063-782de794-f6e8-4e19-8ced-882034c15472.png)

**Comment by timbru** [comment]
Ah okay - it's trying to connect to the parent over https and the connection is refused. This will be fixed in 0.9.5 by the way - it will connect to a local parent without needing an HTTPS call out, and back into itself.

You should be able to solve this by setting up a proxy that allows the connection to that IP address on the standard HTTPS port back to krill which is probably localhost port 3000 if you did not change the defaults.

You could also use a configuration where the `service_uri` points to https://localhost:3000/, but you will have to redo the set up (i.e. delete you data dir content) if you do this. Unfortunately the testbed config is somewhat unforgiving towards making these kinds of changes at a later stage.

If you like you can also send me a direct email at tim nlnetlabs.nl so I can have a look at your config file (remove the admin_token value though I don't need to know it..)  and check that things work for me.

**Comment by gitthehit** [comment]
Thanks again for helping me solve the problem. I have sent email at tim@nlnetlabs.nl. Hope I didn't get the address wrong

**Comment by gitthehit** [comment]
This can be solved by using a dnsmasq, resolving domain name to private IP address.
