### ISSUE TITLE
How to generate the ROA with multiple prefixes

### ISSUE THREAD

**Issue by kaze0912** [NLnetLabs/krill#916]
I want to generate the ROA with multiple prefixes
e.g. ROA1: 192.168.0.0/16,203.18.0.0/16 => 65530
but I only find the way to generate  the ROA with single prefix

How to generate the ROA with multiple prefixes?

**Comment by timbru** [comment]
Can I ask why you want to do this?

There is an active discussion on this, which has been going on for years actually, but which is now also formalised in an active IETF working group document: https://datatracker.ietf.org/doc/draft-ietf-sidrops-roa-considerations/

It is considered best practice to use one ROA per prefix. Most importantly because this reduces the risk of fate sharing validation issues. In your example: if your CA loses 203.18.0.0/16 on the CA certificate it got from its parent, then the combined ROA object would become invalid. I.e. you would also lose the authorisation for AS65530 to announce 192.168.0.0/16.

An exception may be in cases where one has 100s of prefixes. In that case one may decide on a trade-off where the fate sharing risk is accepted in order to avoid a huge amount of objects.

Krill has a built-in default which can be overridden in configuration to start aggregating prefixes per ASN on ROA objects if you have 100 or more prefixes. But this default may be increased in future based on the ongoing discussion in the IETF.

I will close this issue for now, but feel free to re-open if you have more questions or concerns.

**Comment by kaze0912** [comment]
Thank you for your reply.
I made a statistic about ROA, and the result shows that the number of ROAs containing only one prefix is less than 25% of all ROA objects. Therefore, I want to make a comparative experiment on ROA with multiple prefixes and ROA with single prefix.

**Comment by timbru** [comment]
For experiments you can use these settings:

```
#
#                               ROA Aggregation
#
# It is recommended that separate ROAs are used for each authorized prefix, even
# though the RFC allows for multiple prefixes for the same ASN to be combined on
# a single ROA object. The reason for this is that the ROA will become invalid
# if any of the listed prefixes no longer appears on your CA's certificate. Note
# that Krill will automatically clean up over-claiming ROAs when it finds that its
# resources have been shrunk, but there is a possible time window where ROAs can
# be invalid before Krill discovers the shrinkage.
#
# That said, if there would be too many ROAs then this will impact all RPKI
# validators, therefore Krill will by default start aggregating ROAs per ASN
# when more than 100 ROAs would be issued. Conversely, Krill will start de-
# aggregating again when the number of authorizations drops below 90.
#
# This behaviour can be overridden with the following directives:
# roa_aggregate_threshold = 100
# roa_deaggregate_threshold = 90
```

And set roa_aggregate_threshold to 1 and roa_deaggregate_threshold to 0. (at least I think it accepts zero).

**Comment by kaze0912** [comment]
Thanks！
